# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z010clg400-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir {C:/Users/Blythe Tao/Desktop/Embedded/Lab5/Lab5.cache/wt} [current_project]
set_property parent.project_path {C:/Users/Blythe Tao/Desktop/Embedded/Lab5/Lab5.xpr} [current_project]
set_property XPM_LIBRARIES XPM_MEMORY [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_output_repo {c:/Users/Blythe Tao/Desktop/Embedded/Lab5/Lab5.cache/ip} [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files {{C:/Users/Blythe Tao/Desktop/Embedded/Lab5/test.coe}}
add_files {{C:/Users/Blythe Tao/Desktop/Embedded/Lab5/test_data.coe}}
add_files {{C:/Users/Blythe Tao/Desktop/text1.coe}}
add_files {{C:/Users/Blythe Tao/Desktop/text1_data.coe}}
add_files {{C:/Users/Blythe Tao/Desktop/blue1.coe}}
add_files {{C:/Users/Blythe Tao/Desktop/blue1_data.coe}}
add_files {{C:/Users/Blythe Tao/Desktop/bas.coe}}
add_files {{C:/Users/Blythe Tao/Desktop/bas_data.coe}}
read_vhdl -library xil_defaultlib {
  {C:/Users/Blythe Tao/Desktop/Embedded/Lab5/Lab5.srcs/sources_1/imports/new/clock_div.vhd}
  {C:/Users/Blythe Tao/Desktop/Embedded/Lab5/Lab5.srcs/sources_1/imports/new/clock_pixel.vhd}
  {C:/Users/Blythe Tao/Desktop/Embedded/Lab5/Lab5.srcs/sources_1/imports/new/controls.vhd}
  {C:/Users/Blythe Tao/Desktop/Embedded/Lab5/Lab5.srcs/sources_1/imports/new/debounce.vhd}
  {C:/Users/Blythe Tao/Desktop/Embedded/Lab5/Lab5.srcs/sources_1/imports/new/myALU.vhd}
  {C:/Users/Blythe Tao/Desktop/Embedded/Lab5/Lab5.srcs/sources_1/imports/new/pixel_pusher.vhd}
  {C:/Users/Blythe Tao/Desktop/Embedded/Lab5/Lab5.srcs/sources_1/imports/new/regs.vhd}
  {C:/Users/Blythe Tao/Desktop/Embedded/Lab5/Lab5.srcs/sources_1/imports/new/tx.vhd}
  {C:/Users/Blythe Tao/Desktop/Embedded/Lab5/Lab5.srcs/sources_1/imports/new/rx.vhd}
  {C:/Users/Blythe Tao/Desktop/Embedded/Lab5/Lab5.srcs/sources_1/imports/new/uart.vhd}
  {C:/Users/Blythe Tao/Desktop/Embedded/Lab5/Lab5.srcs/sources_1/imports/new/vga_ctrl.vhd}
  {C:/Users/Blythe Tao/Desktop/Embedded/Lab5/Lab5.srcs/sources_1/imports/new/framebuffer.vhd}
  {C:/Users/Blythe Tao/Desktop/Embedded/Lab5/Lab5.srcs/sources_1/bd/design_1/hdl/design_1_wrapper.vhd}
}
add_files {{C:/Users/Blythe Tao/Desktop/Embedded/Lab5/Lab5.srcs/sources_1/bd/design_1/design_1.bd}}
set_property used_in_implementation false [get_files -all {{c:/Users/Blythe Tao/Desktop/Embedded/Lab5/Lab5.srcs/sources_1/bd/design_1/ip/design_1_blk_mem_gen_0_0/design_1_blk_mem_gen_0_0_ooc.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/Blythe Tao/Desktop/Embedded/Lab5/Lab5.srcs/sources_1/bd/design_1/ip/design_1_blk_mem_gen_1_0/design_1_blk_mem_gen_1_0_ooc.xdc}}]
set_property used_in_implementation false [get_files -all {{C:/Users/Blythe Tao/Desktop/Embedded/Lab5/Lab5.srcs/sources_1/bd/design_1/design_1_ooc.xdc}}]
set_property is_locked true [get_files {{C:/Users/Blythe Tao/Desktop/Embedded/Lab5/Lab5.srcs/sources_1/bd/design_1/design_1.bd}}]

foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc {{C:/Users/Blythe Tao/Desktop/Embedded/Lab5/Lab5.srcs/constrs_1/imports/Lab5/ZYBO_Master.xdc}}
set_property used_in_implementation false [get_files {{C:/Users/Blythe Tao/Desktop/Embedded/Lab5/Lab5.srcs/constrs_1/imports/Lab5/ZYBO_Master.xdc}}]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top design_1_wrapper -part xc7z010clg400-1


write_checkpoint -force -noxdef design_1_wrapper.dcp

catch { report_utilization -file design_1_wrapper_utilization_synth.rpt -pb design_1_wrapper_utilization_synth.pb }
